name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v4

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        # Generate the website
        - name: Publish
          run: dotnet publish CaelumWebsite\\CaelumWebsite.csproj --configuration Release -o release

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: release/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            # TODO uncomment the following line if you have a custom domain name
            # cname: demo.meziantou.net
